import type { Metadata } from "next";

import "./globals.css";
import { Document } from "@/components/document";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutProps = Readonly<{
	children: React.ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutProps) {
	return <Document>{children}</Document>;
}
